### ISSUE TITLE
Removing a group membership removes ALL memberships, destroying group hierarchies

### ISSUE THREAD

**Issue by theomega** [cloudfoundry/uaa#765] opened 2018-02-05 16:09 UTC
### What version of UAA are you running?
4.8.3

### How are you deploying the UAA?
Official Maven JAR from Maven Central

#### High Level
If you have the following setup:
 - User is member of g1
 - User is member of g2
 - g1 is member of g2

And you remove the User from g2, then also(!) g1 is removed(!) from g2. Additionally, a strange error message is thrown.

##### Setup:
```
uaac user add bug_tryout_user --emails x@y.io -p user1235678
uaac group add bug_tryout_g1
uaac group add bug_tryout_g2
uaac member add bug_tryout_g1 bug_tryout_user
uaac member add bug_tryout_g2 bug_tryout_user
uaacAddMember bug_tryout_g2 bug_tryout_g1
```
##### Check Everything is correct:
```
$ uaac group get bug_tryout_g2
  id: d0e141e0-af2c-4766-95c0-32603d0e8002
  meta
    version: 1
    created: 2018-02-05T15:58:45.650Z
    lastmodified: 2018-02-05T15:59:28.929Z
  members:
  -
    origin: uaa
    type: GROUP
    value: 16869688-7032-4567-9cb3-17c405f642b6
  -
    origin: uaa
    type: USER
    value: 7d8ddb46-4853-42f7-be37-a53fe3a3e4e9
  schemas: urn:scim:schemas:core:1.0
  displayname: bug_tryout_g2
  zoneid: uaa

$ uaac group get bug_tryout_g1
  id: 16869688-7032-4567-9cb3-17c405f642b6
  meta
    version: 1
    created: 2018-02-05T15:58:41.270Z
    lastmodified: 2018-02-05T15:59:09.576Z
  members:
  -
    origin: uaa
    type: USER
    value: 7d8ddb46-4853-42f7-be37-a53fe3a3e4e9
  schemas: urn:scim:schemas:core:1.0
  displayname: bug_tryout_g1
  zoneid: uaa

$ uaac user get bug_tryout_user | grep try | grep display
    display: bug_tryout_g2
    display: bug_tryout_g1
```
##### Remove the association
Observe the error message which is already unexpected
```
$ uaac member delete bug_tryout_g2 bug_tryout_user

error response:
{
  "error_description": "User 16869688-7032-4567-9cb3-17c405f642b6 does not exist",
  "error": "scim",
  "message": "User 16869688-7032-4567-9cb3-17c405f642b6 does not exist"
}
```

##### Observe the desaster
The g2 group has lost all its members:
```
$ uaac group get bug_tryout_g2
  id: d0e141e0-af2c-4766-95c0-32603d0e8002
  meta
    version: 3
    created: 2018-02-05T15:58:45.650Z
    lastmodified: 2018-02-05T16:02:25.825Z
  members:
  schemas: urn:scim:schemas:core:1.0
  displayname: bug_tryout_g2
  zoneid: uaa
```

### What did you expect to see? What goal are you trying to achieve with the UAA?
I expected that only the association between the user and g2 gets removed

### What did you see instead?
g2 looses all its members.

**Comment by theomega** [comment] 2018-02-05 17:00
I suspect this might be a bug in the uaac and not in the uaa. If I delete the membership through the API endpoints directly, I'm not able to reproduce this. This is quite servere.

**Comment by DennisDenuto** [comment] 2018-03-29 02:58
Hi @theomega  thanks for creating this issue.

Hmm this gets even a little more strange, because I tried the above with `uaa 4.11.0` & `UAAC 4.1.0` and I was unable to reproduce. Can you confirm this is still an issue with newer version of uaa?

```
$ uaac group get bug_tryout_g2

  id: 0adc8b19-0909-46c8-b4a4-4200212212e2
  meta
    version: 1
    created: 2018-03-29T02:40:55.864Z
    lastmodified: 2018-03-29T02:40:56.921Z
  members:
  -
    origin: uaa
    type: GROUP
    value: ae4ffbea-3e24-4daf-85f0-30c39bf4d4a4
  -
    origin: uaa
    type: USER
    value: e5530978-19d2-48db-8f13-25789c31ac05
  schemas: urn:scim:schemas:core:1.0
  displayname: bug_tryout_g2
  zoneid: uaa

$ uaac member delete bug_tryout_g2 bug_tryout_user
success

$ uaac group get bug_tryout_g2

  id: 0adc8b19-0909-46c8-b4a4-4200212212e2
  meta
    version: 2
    created: 2018-03-29T02:40:55.864Z
    lastmodified: 2018-03-29T02:49:24.035Z
  members:
  -
    origin: uaa
    type: GROUP
    value: ae4ffbea-3e24-4daf-85f0-30c39bf4d4a4
  schemas: urn:scim:schemas:core:1.0
  displayname: bug_tryout_g2
  zoneid: uaa
```

**Comment by bernardpletikosa** [comment] 2018-04-16 12:04
Hi @DennisDenuto 
I tried this again with UAA 4.11.0 & UAAC 4.1.0 and I could NOT reproduce this error.
I think we can close this one.

**Closed** 2018-04-16 15:12 UTC
Labels: unscheduled
