### ISSUE TITLE
Feature request: Push builds to official docker registry

### ISSUE THREAD

**Issue by ponyfleisch** [cloudfoundry/uaa#754] opened 2017-12-28 04:03 UTC
Now that there is a build task to build a docker image (#673) would it be possible to have official builds pushed into the docker registry?

**Comment by tnwang** [comment] 2018-03-20 01:20
Closing this as the original PR was intended to only be for developer use, not a full feature docker image of UAA.

**Closed by tnwang** 2018-03-20 01:20 UTC
Labels: unscheduled
