### ISSUE TITLE
UAA client create/update should accept wildcard in redirect_uri port

### ISSUE THREAD

**Issue by abh1kg** [cloudfoundry/uaa#679] opened 2017-08-21 08:41 UTC
```
uaac --debug client add test_client -i
New client secret:  ****
Verify new client secret:  ****
scope (list):  cloud_controller.read
authorized grant types (list):  authorization_code
authorities (list):
access token validity (seconds):
refresh token validity (seconds):
redirect uri (list):  http://localhost:*/test/path
autoapprove (list):
signup redirect url (url):

error response:
{
  "error": "invalid_client",
  "error_description": "One of the redirect_uri is invalid: http://localhost:*/test/path"
}
```

Similar redirect URI patterns worked earlier but redirection with the saved clients also fail now. This hampers local development quite a lot because only a specified port can be used in the redirect URL definition

**Comment by jhamon** [comment] 2017-08-22 20:42
In a recent release of UAA we added some security restrictions around which part of the `redirect_uri` may be wildcarded. Domains, specifically, were one big area of concern because of the way subdomain routes are assigned to other CF tenants that may not be considered trusted.

We're discussing internally whether the wildcarding of ports should be allowed or not.

**Comment by sreetummidi** [comment] 2017-09-28 20:50
@fhanik @jhamon @tnwang I had a discussion with the GE team yesterday. I have asked them to make the following changes in the PR. 


1. Introduce the concept of whitelisting allowed redirect uri protocols at the zone level The default is HTTP and HTTPS
2. When create clients needing redirect uri, we will validate against the zone whitelist


Apart from this, this PR also contains allowing regex pattern for redirect port. I have asked them to keep these code changes intact within the PR

Thanks,
Sree

**Comment by RoopGuron** [comment] 2017-10-03 21:15
@sreetummidi As we at GE are implementing the protocol whitelisting, we have noticed a break in backward compatibility caused by whitelisting. Even though its impact for GE is minimal we do want to bring this to your attention.

The protocol pattern has been for quite some time(At least since Feb this year) on the lines of
`^(http(\\*|s)?://)"    //URL starts with 'http://' or 'https://' or 'http*://`
But changing this to a protocol whitelisting (for default uaa zone) would be: 
`^(http|https)://`
Thus any clients registered with redirectUris using wildcard in the protocol part would not work for  authorization grant.
There is an explicit test `org.cloudfoundry.identity.uaa.mock.token.TokenMvcMockTests#testWildcardRedirectURL`
which sets up a redirectURI: 
`String redirectUri = "http*://subdomain.domain.com/**/path2?query1=value1";` which would fail and would need to be changed or removed.

We at GE are not impacted much by this backward compatible breaking whitelisting as we do not have any known client registrations with redirectURIs using the wildcard.

**Comment by ilipkind** [comment] 2017-10-03 21:42
@sreetummidi essentially we are asking if we need to support protocol scheme http* like httpblah. Not sure what is a reason for it. Keep in mind it can be also added per zone using whitelisting. In my view supporting ^(http|https):// by default should be sufficient.

**Comment by tnwang** [comment] 2017-10-26 23:07
Hi @ilipkind, I believe the reason http*:// was used was to allow operators to only enter whitelist URLs once and support both HTTP and HTTPS. This was for operators with very large whitelists, and http* conveniently cut their whitelist size in half compared to having to put in both http and https.

Keeping "http*" then gives us the above behavior as well as backwards compatibility, with the downside that junk protocols like http-this-is-a-fake-protocol:// will also work.

**Closed** 2018-01-25 23:43 UTC
Labels: feature request, unscheduled

**Comment by 6palace** [comment] 2018-04-11 19:08
@jhamon Hi Jen, did you guys ever come to a conclusion on port wildcards? We just realized that https://www.pivotaltracker.com/n/projects/997278/stories/154735792 only addressed custom protocols and did not allow port wildcards.

**Comment by tnwang** [comment] 2018-04-11 22:37
Hi @6palace, could you let us know what use case the ports apply to? Is this something around how mobile applications utilize ports for redirect URIs?

We take PRs :)
