### ISSUE TITLE
Invitations endpoint invalidates invitation code on GET request

### ISSUE THREAD

**Issue by andreasf** [cloudfoundry/uaa#1374] opened 2020-08-11 11:09 UTC
### What version of UAA are you running?

74.5.18

### How are you deploying the UAA?

I am not deploying it myself, it's an internal system (PCFone).

### What did you do?

I invited a new member to my org in order to get username/password credentials for a CI pipeline. The invitation was sent to my phone, from which I forwarded it to my work computer via iMessage. iMessage opened the invitation page in order to preview the link—this invalidated the invitation code.

### What did you expect to see? What goal are you trying to achieve with the UAA?

I expected the invitation code to still work when I opened it in the browser, because I never used the code to create an account.

GET requests should not modify the state of a resource.

### What did you see instead?

UAA showed the following error message: "Your invitation code has expired. Please request another."

The invitation code got invalidated when the link was first opened. In my case the culprit was probably iMessage, but enterprise email screening systems also tend to open links.

* [InvitationsController retrieves code from ExpiringCodeStore](https://github.com/cloudfoundry/uaa/blob/7ca91e2580b394937f3bae8d18187c198cdf62e9/server/src/main/java/org/cloudfoundry/identity/uaa/invitations/InvitationsController.java#L119)
* [JdbcExpiringCodeStore invalidates on retrieval](https://github.com/cloudfoundry/uaa/blob/7ca91e2580b394937f3bae8d18187c198cdf62e9/server/src/main/java/org/cloudfoundry/identity/uaa/codestore/JdbcExpiringCodeStore.java#L125)

**Comment by shamus** [comment] 2020-08-11 15:47
This is by design. Invitations, password resets, etc. generate links that include a one time passcode (OTP). The OTP grants the user limited access to assert control over an account which they previously not been able to access.

These links aren't meant to be forwarded or shared. And, sadly, they will be invalidated by a link previewer.

With respect to this statement:
> GET requests should not modify the state of a resource.

The resource in question is the account, not the passcode, and the account hasn't been modified. For example, if the user has forgotten their password, the password remains unchanged by following the link with the OTP.

I understand that the behavior might be surprising. It's a tradeoff between usability and security.

**Closed as completed by shamus** 2020-08-11 15:47 UTC
Labels: accepted

**Comment by sudhirrs** [comment] 2020-09-24 17:52
I don't think the security implications are that bad - since that token can be used only once and has a time expiry. 
The usability problem is far worse. Outlook web client for example has link previews enabled by default. So the whole password reset experience would be broken for them unless they go and turn it off in their options. I can imagine email scanning solutions that check for suspicious links to break these one time tokens.
At the least, would like some options to configure this behavior with the reset password token validated and destroyed when setting the new password and not on just visiting the link.
