### ISSUE TITLE
UAA should accept url-escaped client credentials via basic auth

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/uaa#785] opened 2018-03-03 04:43 UTC
### What version of UAA are you running?

4.10.0

### How are you deploying the UAA?

I am deploying the UAA using BOSH

### What did you do?

Tried to obtain an access token via client credentials grant where client secret contains url-unsafe characters, using https://godoc.org/golang.org/x/oauth2.

### What did you expect to see? What goal are you trying to achieve with the UAA?

To obtain an access token.

### What did you see instead?

Received a 401.

The golang oauth2 client url-escapes the client id and secret: https://github.com/golang/oauth2/blob/master/internal/token.go#L191. When the client id or secret includes url-unsafe characters, it's impossible to obtain an access token using the golang client, since the uaa doesn't accept url-escaped credentials. It's possible to obtain an access token with url-unsafe credentials using another client, like `curl`, if credentials are not url-escaped.

According to [rfc 6749](https://tools.ietf.org/html/rfc6749#section-2.3.1), client credentials should be url-escaped, so it looks like the behavior of the golang oauth2 client is correct.

cc @sharms @wjwoodson

**Comment by aeijdenberg** [comment] 2018-03-03 05:08
See also https://github.com/cloudfoundry/uaa/issues/778 and https://github.com/cloudfoundry/cli/pull/1176#pullrequestreview-48214051

**Comment by DennisDenuto** [comment] 2018-04-13 02:44
Thanks for creating this issue, reading `rfc6749` I think you are correct. However the `uaa` heavily relies on spring filters to provide `Basic Auth` functionality. Specifically as part of our filter chain we delegate to [BasicAuthenticationFilter](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java#L163). 

This filter in turn adheres to [rfc 1945](https://tools.ietf.org/html/rfc1945) and correctly does not url-decode the base64 token (https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java#L224)

FYI `rfc1945` is dated May 1996 while `rfc6749` is dated Oct 2012. 

I think this issue is valid however I think it belongs in https://github.com/spring-projects/spring-security/issues . If this change is made upstream I think we should be able to upgrade uaa to also conform to `rfc6749`.

**Comment by DennisDenuto** [comment] 2018-04-13 02:49
Closing as it is a duplicate of https://github.com/cloudfoundry/uaa/issues/778

**Closed by DennisDenuto** 2018-04-13 02:49 UTC
Labels: unscheduled
