### ISSUE TITLE
The memory session store has memory leak ?

### ISSUE THREAD

**Issue by JimmyMa** [cloudfoundry/uaa#1150] opened 2019-11-28 05:15 UTC
# What version of UAA are you running?

v74.7.0

### How are you deploying the UAA?

I am deploying the UAA

- using cf-deployment

### What is the problem ?

The UAA memory usage got increased constantly, as below, when the memory usage got to about 800M, UAA reported `Out Of Memeory` exception.

![image](https://user-images.githubusercontent.com/5013209/69778524-94cc0800-11df-11ea-9836-ab82b933565b.png)

### The possible root cause

This line https://github.com/cloudfoundry/uaa/blob/develop/server/src/main/java/org/cloudfoundry/identity/uaa/web/beans/UaaMemorySessionConfig.java#L33, as below, is using `ConcurrentHashMap`, but the MapSessionRepository doc https://docs.spring.io/spring-session/docs/current/api/org/springframework/session/MapSessionRepository.html says `Note that the supplied map itself is responsible for purging the expired sessions.`,  the `ConcurrentHashMap' doesn't has the capability to purge the expired sessions, that caused memory leak.

```
    @Bean
    public MapSessionRepository sessionRepository(final @Value("${servlet.idle-timeout:1800}") int idleTimeout) {
        MapSessionRepository sessionRepository = new MapSessionRepository(new ConcurrentHashMap<>());
        sessionRepository.setDefaultMaxInactiveInterval(idleTimeout);
        return sessionRepository;
    }
```

The heap dump of UAA shows a lot of `MapSession` instances, that's possible an envidence about the leak caused by `ConcurrentHashMap`

```
2198060 instances of class org.springframework.security.core.authority.SimpleGrantedAuthority
168276 instances of class org.springframework.session.MapSession
115556 instances of class 
```

**Comment by strehle** [comment] 2019-11-28 08:05
@mwdb FYI

**Comment by shamus** [comment] 2019-11-29 20:04
Thanks for the report.  I think you are correct that this is quite likely the cause.

I'm mid-fix, but progress is choppy given the holiday here in the US. :)

**Comment by shamus** [comment] 2019-11-30 17:40
I have submitted a PR which should resolve this issue. https://github.com/cloudfoundry/uaa/pull/1152

My colleague @joshuatcasey appears to have independently submitted a PR as well https://github.com/cloudfoundry/uaa/pull/1151

So you have options I guess :)

**Comment by shamus** [comment] 2019-12-03 16:42
Hi there, there's a new release that addresses this behavior

https://github.com/cloudfoundry/uaa/releases/tag/v74.12.0

I'll close this issue out unless there are other concerns?

**Closed as completed** 2019-12-04 19:26 UTC
